// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RapidPay.PaymentFees.EntityFramework;

#nullable disable

namespace RapidPay.PaymentFees.EntityFramework.Migrations
{
    [DbContext(typeof(PayamentFeesContext))]
    partial class PayamentFeesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RapidPay.PaymentFees.Domain.Models.Fee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("feeid");

                    b.Property<DateTime>("Effectivedate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effectivedate");

                    b.Property<decimal>("Feerate")
                        .HasColumnType("numeric")
                        .HasColumnName("feerate");

                    b.HasKey("Id");

                    b.ToTable("fees", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
